# Generated by Django 5.0.6 on 2024-06-09 10:57

import django.contrib.postgres.fields
import django.db.models.deletion
import netlibrary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'netlibrary_genre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_rating', models.BigIntegerField(default=0, verbose_name='Положительный рейтинг')),
                ('negative_rating', models.BigIntegerField(default=0, verbose_name='Отрицательный рейтинг')),
                ('final_raiting', models.BigIntegerField(default=0, verbose_name='Итоговый рейтинг')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'db_table': 'netlibrary_rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='Обложка')),
                ('book', models.FileField(upload_to='books/', verbose_name='Книга')),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Автора'), blank=True, default=netlibrary.models.default_authors, size=None, verbose_name='Авторы')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netlibrary.genre')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='netlibrary.rating')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'db_table': 'netlibrary_book',
                'managed': True,
            },
        ),
    ]
